name: Setup Consul Environmant

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix: 
        python-version : [3.6]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install docker compose
        run: pip install docker-compose

      - name: Start docker services
        run: docker-compose up -d --build

      - name: Run sanity check
        run: docker-compose exec -T consul bash -c "consul validate /consul/consul.d/server/config.json"

      - name: Create and read test key using the REST API
        run: |
            export MASTER_TOKEN=9beb4f8e-7220-41d2-946c-b8a8e3574692
            curl --header "X-Consul-Token: $MASTER_TOKEN" --request PUT --data "ofir_test" http://127.0.0.1:8500/v1/kv/test
            curl --header "X-Consul-Token: $MASTER_TOKEN" --request GET http://127.0.0.1:8500/v1/kv/test