name: Setup Consul Environment CI

on:
  push:
    branches: [ master ]

jobs:
  site-config-deployment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Make sure docker-compose is installed
        run: docker-compose version

      - name: Make sure consul service is up and running
        run: docker-compose exec -T consul bash -c "consul version"

      - name: Restart Consul container to load new configuration
        run: docker-compose down && docker-compose up -d --build

      - name: Run consul configuration sanity check
        run: docker-compose exec -T consul bash -c "consul validate /consul/config/config.json"

      - name: Make sure site-a service is available
        run: |
          export TOKEN=$(cat /opt/hashicorp/consul/consul.d/server/config.json | grep agent | awk '{print substr($2, 1, length($2)-2)}' | tr -d \")
          curl -i --header "X-Consul-Token: $TOKEN" --request GET http://127.0.0.1:8500/v1/catalog/service/site-a